import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import type { AudioPlayer } from 'expo-audio';

/**
 * One-shot sound effects.
 *
 * The clips were generated by `scripts/generate-sounds.js`, which renders the
 * same oscillators the HTML prototype synthesised at runtime. They are short
 * (0.05 s – 0.7 s) so they can be fired on every tap.
 */

export type SoundName =
  | 'click'
  | 'tap'
  | 'chime'
  | 'ding'
  | 'buzz'
  | 'hit'
  | 'triumph'
  | 'swoosh'
  | 'clear';

const SOURCES: Record<SoundName, number> = {
  click: require('../../assets/sounds/click.wav'),
  tap: require('../../assets/sounds/tap.wav'),
  chime: require('../../assets/sounds/chime.wav'),
  ding: require('../../assets/sounds/ding.wav'),
  buzz: require('../../assets/sounds/buzz.wav'),
  hit: require('../../assets/sounds/hit.wav'),
  triumph: require('../../assets/sounds/triumph.wav'),
  swoosh: require('../../assets/sounds/swoosh.wav'),
  clear: require('../../assets/sounds/clear.wav'),
};

/**
 * One player per sound, created on first use and kept for the life of the app.
 * There are only nine of them, and re-creating a player on every tap would
 * leak native resources — so we deliberately never release these.
 */
const players: Partial<Record<SoundName, AudioPlayer>> = {};

let enabled = true;
let configured = false;

/**
 * Play through the silent switch and duck nothing.
 * A timer's chime has to be audible even when the phone is on silent.
 */
export async function initAudio(): Promise<void> {
  if (configured) return;
  configured = true;

  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      interruptionMode: 'mixWithOthers',
    });
  } catch {
    // Audio is a nicety; never let it take the app down.
  }
}

function playerFor(name: SoundName): AudioPlayer | null {
  const existing = players[name];
  if (existing) return existing;

  try {
    const created = createAudioPlayer(SOURCES[name]);
    players[name] = created;
    return created;
  } catch {
    return null;
  }
}

/** Fire a sound effect. Safe to call on every interaction. */
export function playSound(name: SoundName): void {
  if (!enabled) return;

  void initAudio();

  const player = playerFor(name);
  if (!player) return;

  try {
    player.seekTo(0);
  } catch {
    // A failed rewind must not stop the sound from playing.
  }

  try {
    player.play();
  } catch {
    // A failed sound must never break the interaction it was decorating.
  }
}

/** Driven by the "Sound effects" setting. */
export function setSoundEnabled(next: boolean): void {
  enabled = next;
}
